version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "GMT"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      include: "scope"
    cooldown:
      semver-major-days: 14
      semver-minor-days: 3
      semver-patch-days: 1
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "GMT"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      include: "scope"
    cooldown:
      semver-major-days: 14
      semver-minor-days: 3
      semver-patch-days: 1
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "GMT"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      include: "scope"
    cooldown:
      semver-major-days: 14
      semver-minor-days: 3
      semver-patch-days: 1
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pre-commit"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "GMT"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      include: "scope"
    cooldown:
      semver-major-days: 14
      semver-minor-days: 3
      semver-patch-days: 1
    groups:
      pre-commit-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
